export const REGISTER_ACTION = "REGISTER";
export const AUTH_ACTION = "AUTH";

export const POST_TAG_ACTION = "POST_TAG";
export const GET_TAG_ACTION = "GET_TAG";
export const PUT_TAG_ACTION = "PUT_TAG";
export const DELETE_TAG_ACTION = "DELETE_TAG";

export const POST_CATEGORY_ACTION = "POST_CATEGORY";
export const GET_CATEGORY_ACTION = "GET_CATEGORY";
export const PUT_CATEGORY_ACTION = "PUT_CATEGORY";
export const DELETE_CATEGORY_ACTION = "DELETE_CATEGORY";

export const POST_COMMENT_ACTION = "POST_COMMENT";
export const GET_COMMENT_ACTION = "GET_COMMENT";
export const PUT_COMMENT_ACTION = "PUT_COMMENT";
export const DELETE_COMMENT_ACTION = "DELETE_COMMENT";

export const POST_RELATIONSHIP_ACTION = "POST_RELATIONSHIP";
export const GET_RELATIONSHIP_ACTION = "GET_RELATIONSHIP";
export const PUT_RELATIONSHIP_ACTION = "PUT_RELATIONSHIP";
export const DELETE_RELATIONSHIP_ACTION = "DELETE_RELATIONSHIP";

export const POST_EVENT_ACTION = "POST_EVENT";
export const GET_EVENT_ACTION = "GET_EVENT";
export const PUT_EVENT_ACTION = "PUT_EVENT";
export const DELETE_EVENT_ACTION = "DELETE_EVENT";

export const POST_USER_ACTION = "POST_USER";
export const GET_USERS_ACTION = "GET_USERS";
export const GET_USER_ACTION = "GET_USER";
export const GET_USER_FRIENDS_ACTION = "GET_USER_FRIENDS";
export const GET_USER_EVENTS_IN_INTERVAL_ACTION = "GET_USER_EVENTS_IN_INTERVAL";
export const GET_USER_FRIENDS_EVENTS_IN_INTERVAL_ACTION = "GET_USER_FRIENDS_EVENTS_IN_INTERVAL";
export const PUT_USER_ACTION = "PUT_USER";
export const DELETE_USER_ACTION = "DELETE_USER";
export const DELETE_USER_FRIENDS_ACTION = "DELETE_USER_FRIENDS";
export const DELETE_USER_EVENTS_ACTION = "DELETE_USER_EVENTS";
export const DELETE_USER_TEMPLATES_ACTION = "DELETE_USER_TEMPLATES";

export const POST_TEMPLATE_ACTION = "POST_TEMPLATE";
export const CREATE_TEMPLATE_EVENTS_ACTION = "CREATE_TEMPLATE_EVENTS";
export const GET_TEMPLATE_ACTION = "GET_TEMPLATE";
export const PUT_TEMPLATE_AND_TEMPLATE_EVENTS_ACTION = "PUT_TEMPLATE_AND_TEMPLATE_EVENTS";
export const DELETE_TEMPLATE_AND_TEMPLATE_EVENTS_ACTION = "DELETE_TEMPLATE_AND_TEMPLATE_EVENTS";
export const DELETE_TEMPLATE_EVENTS_ACTION = "DELETE_TEMPLATE_EVENTS";